from PyQt5 import uic
from PyQt5.QtWidgets import QMainWindow, QLabel, QTextEdit, QPushButton
#from qt_material import apply_stylesheet

class UI(QMainWindow):
    def __init__(self):
        super(UI, self).__init__()
        # load UI from file (generated by Qt Designer
        uic.loadUi("main.ui", self)
        # link to UI widgets
        self.input_sql = self.findChild(QTextEdit, "input_query")
        self.label_qep = self.findChild(QLabel, "text_plan")
        self.btn_analyse = self.findChild(QPushButton, "btn_analyse")
        self.btn_clear = self.findChild(QPushButton, "btn_clear")
        # init widgets
        self.btn_clear.clicked.connect(self.clear)
        
    def clear(self):
        self.input_sql.setPlainText("")
        self.label_qep.setText("")
        
    def readInput(self):
        return self.input_sql.toPlainText()
    
    def setResult(self, text):
        self.label_qep.setText(text)
    
    def setOnClicked(self, callback):
        self.btn_analyse.clicked.connect(callback)

'''
# maybe this part move to main script
if __name__ == "__main__":
    app = QApplication(sys.argv)
    apply_stylesheet(app, theme="light_cyan_500.xml")
    window = UI()
    
    # assigning callback
    window.setOnClicked(
        lambda: window.setResult( window.readInput() )
    )
    window.show()
    sys.exit(app.exec_())
'''